export type VenueRegistryEntry = {
  key: string;
  label: string;
  venueName: string;
  city: string;
  timezone: string;
  officialCalendarUrl: string;
  rssUrl: string | null;
  icsUrl: string | null;
  snsAccount: string | null;
};

export const OFFICIAL_VENUE_REGISTRY: VenueRegistryEntry[] = [
  // Japan - Tokyo
  {
    key: "tokyo_womb",
    label: "WOMB Tokyo",
    venueName: "WOMB",
    city: "Tokyo",
    timezone: "Asia/Tokyo",
    officialCalendarUrl: "https://www.womb.co.jp/en/event/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@WOMB_Tokyo",
  },
  {
    key: "tokyo_contact",
    label: "Contact Tokyo",
    venueName: "Contact",
    city: "Tokyo",
    timezone: "Asia/Tokyo",
    officialCalendarUrl: "https://www.contacttokyo.com/schedule/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@contacttokyo",
  },
  {
    key: "tokyo_oeast",
    label: "Spotify O-EAST Tokyo",
    venueName: "Spotify O-EAST",
    city: "Tokyo",
    timezone: "Asia/Tokyo",
    officialCalendarUrl: "https://shibuya-o.com/east/schedule/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@shibuyao_group",
  },
  {
    key: "tokyo_owest",
    label: "Spotify O-WEST Tokyo",
    venueName: "Spotify O-WEST",
    city: "Tokyo",
    timezone: "Asia/Tokyo",
    officialCalendarUrl: "https://shibuya-o.com/west/schedule/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@shibuyao_group",
  },
  {
    key: "tokyo_duo",
    label: "duo MUSIC EXCHANGE Tokyo",
    venueName: "duo MUSIC EXCHANGE",
    city: "Tokyo",
    timezone: "Asia/Tokyo",
    officialCalendarUrl: "https://www.duomusicexchange.com/schedule/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@duomusicexchange",
  },
  {
    key: "tokyo_liquidroom",
    label: "LIQUIDROOM Tokyo",
    venueName: "LIQUIDROOM",
    city: "Tokyo",
    timezone: "Asia/Tokyo",
    officialCalendarUrl: "https://www.liquidroom.net/schedule",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@LIQUIDROOM",
  },
  {
    key: "tokyo_zepp_shinjuku",
    label: "Zepp Shinjuku",
    venueName: "Zepp Shinjuku",
    city: "Tokyo",
    timezone: "Asia/Tokyo",
    officialCalendarUrl: "https://www.zepp.co.jp/hall/shinjuku/schedule/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@zepphall",
  },
  // Japan - Osaka
  {
    key: "osaka_bananahall",
    label: "BananaHall Osaka",
    venueName: "BananaHall",
    city: "Osaka",
    timezone: "Asia/Tokyo",
    officialCalendarUrl: "https://www.bananahall.jp/schedule/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@bananahallosaka",
  },
  {
    key: "osaka_zepp_namba",
    label: "Zepp Namba",
    venueName: "Zepp Namba",
    city: "Osaka",
    timezone: "Asia/Tokyo",
    officialCalendarUrl: "https://www.zepp.co.jp/hall/namba/schedule/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@zepphall",
  },
  // UK
  {
    key: "london_fabric",
    label: "fabric London",
    venueName: "fabric",
    city: "London",
    timezone: "Europe/London",
    officialCalendarUrl: "https://www.fabriclondon.com/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@fabriclondon",
  },
  {
    key: "london_roundhouse",
    label: "Roundhouse London",
    venueName: "Roundhouse",
    city: "London",
    timezone: "Europe/London",
    officialCalendarUrl: "https://www.roundhouse.org.uk/whats-on/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@RoundhouseLDN",
  },
  {
    key: "london_koko",
    label: "KOKO London",
    venueName: "KOKO",
    city: "London",
    timezone: "Europe/London",
    officialCalendarUrl: "https://koko.co.uk/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@KOKOLondon",
  },
  // Germany
  {
    key: "berlin_tresor",
    label: "Tresor Berlin",
    venueName: "Tresor",
    city: "Berlin",
    timezone: "Europe/Berlin",
    officialCalendarUrl: "https://tresorberlin.com/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@tresorberlin",
  },
  {
    key: "berlin_watergate",
    label: "Watergate Berlin",
    venueName: "Watergate",
    city: "Berlin",
    timezone: "Europe/Berlin",
    officialCalendarUrl: "https://water-gate.de/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@watergate_club",
  },
  {
    key: "berlin_berghain",
    label: "Berghain Berlin",
    venueName: "Berghain",
    city: "Berlin",
    timezone: "Europe/Berlin",
    officialCalendarUrl: "https://www.berghain.berlin/en/program/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@berghain",
  },
  // USA - New York
  {
    key: "ny_brooklyn_mirage",
    label: "Brooklyn Mirage",
    venueName: "Brooklyn Mirage",
    city: "New York",
    timezone: "America/New_York",
    officialCalendarUrl: "https://www.avant-gardner.com/events",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@avantgardnerbk",
  },
  {
    key: "ny_nowadays",
    label: "Nowadays NYC",
    venueName: "Nowadays",
    city: "New York",
    timezone: "America/New_York",
    officialCalendarUrl: "https://nowadays.nyc/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@nowadaysnyc",
  },
  {
    key: "ny_knockdown",
    label: "Knockdown Center NYC",
    venueName: "Knockdown Center",
    city: "New York",
    timezone: "America/New_York",
    officialCalendarUrl: "https://knockdown.center/upcoming/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@knockdowncenter",
  },
  // USA - Los Angeles
  {
    key: "la_hollywood_palladium",
    label: "Hollywood Palladium LA",
    venueName: "Hollywood Palladium",
    city: "Los Angeles",
    timezone: "America/Los_Angeles",
    officialCalendarUrl: "https://www.hollywoodpalladium.com/events",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@PalladiumLA",
  },
  {
    key: "la_the_novo",
    label: "The Novo LA",
    venueName: "The Novo",
    city: "Los Angeles",
    timezone: "America/Los_Angeles",
    officialCalendarUrl: "https://www.thenovodtla.com/events",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@thenovodtla",
  },
  // France - Paris
  {
    key: "paris_olympia",
    label: "L'Olympia Paris",
    venueName: "L'Olympia",
    city: "Paris",
    timezone: "Europe/Paris",
    officialCalendarUrl: "https://www.olympiahall.com/agenda/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@OLYMPIAHALL",
  },
  {
    key: "paris_accor_arena",
    label: "Accor Arena Paris",
    venueName: "Accor Arena",
    city: "Paris",
    timezone: "Europe/Paris",
    officialCalendarUrl: "https://www.accorarena.com/en/events-and-tickets",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@Accor_Arena",
  },
  {
    key: "paris_badaboum",
    label: "Badaboum Paris",
    venueName: "Badaboum",
    city: "Paris",
    timezone: "Europe/Paris",
    officialCalendarUrl: "https://badaboum.paris/agenda/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@badaboumparis",
  },
  // Netherlands - Amsterdam
  {
    key: "ams_shelter",
    label: "Shelter Amsterdam",
    venueName: "Shelter Amsterdam",
    city: "Amsterdam",
    timezone: "Europe/Amsterdam",
    officialCalendarUrl: "https://www.shelteramsterdam.nl/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@shelteradam",
  },
  {
    key: "ams_radion",
    label: "RADION Amsterdam",
    venueName: "RADION",
    city: "Amsterdam",
    timezone: "Europe/Amsterdam",
    officialCalendarUrl: "https://www.radion.amsterdam/program",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@radionamsterdam",
  },
  {
    key: "ams_thuishaven",
    label: "Thuishaven Amsterdam",
    venueName: "Thuishaven",
    city: "Amsterdam",
    timezone: "Europe/Amsterdam",
    officialCalendarUrl: "https://thuishaven.nl/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@thuishaven",
  },
  {
    key: "ams_dgtl",
    label: "DGTL Amsterdam",
    venueName: "DGTL Amsterdam",
    city: "Amsterdam",
    timezone: "Europe/Amsterdam",
    officialCalendarUrl: "https://dgtl.nl/amsterdam/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@dgtlfestival",
  },
  {
    key: "ams_awakenings",
    label: "Awakenings",
    venueName: "Awakenings",
    city: "Amsterdam",
    timezone: "Europe/Amsterdam",
    officialCalendarUrl: "https://www.awakenings.com/en/events",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@awakenings",
  },
  // Jamaica
  {
    key: "jm_tuff_gong",
    label: "Tuff Gong Studios",
    venueName: "Tuff Gong Studios",
    city: "Kingston",
    timezone: "America/Jamaica",
    officialCalendarUrl: "https://tuffgong.com/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@tuffgong",
  },
  {
    key: "jm_reggae_sumfest",
    label: "Reggae Sumfest",
    venueName: "Reggae Sumfest",
    city: "Montego Bay",
    timezone: "America/Jamaica",
    officialCalendarUrl: "https://reggaesumfest.com/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@reggaesumfest",
  },
  // Middle East - Outdoor rave / festival scenes
  {
    key: "sa_mdlbeast",
    label: "MDLBEAST Saudi",
    venueName: "MDLBEAST",
    city: "Riyadh",
    timezone: "Asia/Riyadh",
    officialCalendarUrl: "https://mdlbeast.com/events",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@MDLBEAST",
  },
  {
    key: "ae_sundream",
    label: "Sundream Dubai",
    venueName: "Sundream",
    city: "Dubai",
    timezone: "Asia/Dubai",
    officialCalendarUrl: "https://www.sundream.com/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@sundream",
  },
  {
    key: "eg_sandbox",
    label: "Sandbox Festival Egypt",
    venueName: "Sandbox Festival",
    city: "Cairo",
    timezone: "Africa/Cairo",
    officialCalendarUrl: "https://sandboxfestival.com/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@sandboxfestival",
  },
  {
    key: "jo_distant_heat",
    label: "Distant Heat Jordan",
    venueName: "Distant Heat",
    city: "Amman",
    timezone: "Asia/Amman",
    officialCalendarUrl: "https://www.distant-heat.com/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@distantheat",
  },
  // Thailand - Full Moon Party and outdoor rave scenes
  {
    key: "th_fullmoon_haadrin",
    label: "Full Moon Party Haad Rin",
    venueName: "Haad Rin Beach",
    city: "Koh Phangan",
    timezone: "Asia/Bangkok",
    officialCalendarUrl: "https://fullmoonparty-thailand.com/schedules/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@fullmoonpartythailand",
  },
  {
    key: "th_halfmoon_festival",
    label: "Halfmoon Festival Koh Phangan",
    venueName: "Halfmoon Festival",
    city: "Koh Phangan",
    timezone: "Asia/Bangkok",
    officialCalendarUrl: "https://halfmoonfestival.com/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@halfmoonfestival",
  },
  {
    key: "th_jungle_experience",
    label: "Jungle Experience Koh Phangan",
    venueName: "Jungle Experience",
    city: "Koh Phangan",
    timezone: "Asia/Bangkok",
    officialCalendarUrl: "https://jungle-experience.com/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@jungleexperience",
  },
  {
    key: "th_edens_garden",
    label: "Eden Garden Party Koh Phangan",
    venueName: "Eden Garden",
    city: "Koh Phangan",
    timezone: "Asia/Bangkok",
    officialCalendarUrl: "https://www.eden-thailand.com/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@edengardenparty",
  },
  {
    key: "th_s2o_bangkok",
    label: "S2O Songkran Music Festival",
    venueName: "S2O Festival",
    city: "Bangkok",
    timezone: "Asia/Bangkok",
    officialCalendarUrl: "https://s2ofestival.com/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@s2ofestival",
  },
  // Australia
  {
    key: "au_sydney_ivy",
    label: "ivy Sydney",
    venueName: "ivy Sydney",
    city: "Sydney",
    timezone: "Australia/Sydney",
    officialCalendarUrl: "https://merivale.com/venues/ivy/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@merivale",
  },
  {
    key: "au_sydney_hordern",
    label: "Hordern Pavilion Sydney",
    venueName: "Hordern Pavilion",
    city: "Sydney",
    timezone: "Australia/Sydney",
    officialCalendarUrl: "https://hordernpavilion.com.au/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@hordernpavilion",
  },
  {
    key: "au_melbourne_revolver",
    label: "Revolver Upstairs Melbourne",
    venueName: "Revolver Upstairs",
    city: "Melbourne",
    timezone: "Australia/Melbourne",
    officialCalendarUrl: "https://www.revolverupstairs.com.au/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@revolverupstairs",
  },
  // Brazil
  {
    key: "br_rio_greenvalley",
    label: "Green Valley Brazil",
    venueName: "Green Valley",
    city: "Camboriu",
    timezone: "America/Sao_Paulo",
    officialCalendarUrl: "https://www.greenvalleybr.com/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@greenvalleybr",
  },
  {
    key: "br_sao_laroc",
    label: "Laroc Club Brazil",
    venueName: "Laroc Club",
    city: "Sao Paulo",
    timezone: "America/Sao_Paulo",
    officialCalendarUrl: "https://www.laroc.club/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@larocclub",
  },
  {
    key: "br_universo_paralello",
    label: "Universo Paralello Brazil",
    venueName: "Universo Paralello",
    city: "Pratigi",
    timezone: "America/Bahia",
    officialCalendarUrl: "https://universoparalello.org/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@universoparalello",
  },
  // Spain
  {
    key: "es_ibiza_hii",
    label: "Hï Ibiza",
    venueName: "Hï Ibiza",
    city: "Ibiza",
    timezone: "Europe/Madrid",
    officialCalendarUrl: "https://www.hiibiza.com/events",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@hiibizaofficial",
  },
  {
    key: "es_ibiza_dc10",
    label: "DC-10 Ibiza",
    venueName: "DC-10",
    city: "Ibiza",
    timezone: "Europe/Madrid",
    officialCalendarUrl: "https://www.dc10ibiza.com/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@dc10ibiza",
  },
  {
    key: "es_monegros",
    label: "Monegros Desert Festival",
    venueName: "Monegros Festival",
    city: "Fraga",
    timezone: "Europe/Madrid",
    officialCalendarUrl: "https://monegrosfestival.com/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@monegrosfestival",
  },
  // Canada
  {
    key: "ca_toronto_rebel",
    label: "REBEL Toronto",
    venueName: "REBEL Toronto",
    city: "Toronto",
    timezone: "America/Toronto",
    officialCalendarUrl: "https://rebeltoronto.com/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@rebeltoronto",
  },
  {
    key: "ca_montreal_newcitygas",
    label: "New City Gas Montreal",
    venueName: "New City Gas",
    city: "Montreal",
    timezone: "America/Toronto",
    officialCalendarUrl: "https://newcitygas.com/en/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@newcitygas",
  },
  {
    key: "ca_vancouver_commodore",
    label: "Commodore Ballroom Vancouver",
    venueName: "Commodore Ballroom",
    city: "Vancouver",
    timezone: "America/Vancouver",
    officialCalendarUrl: "https://commodoreballroom.com/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@commodoreballroom",
  },
  // UK - Bristol
  {
    key: "uk_bristol_motion",
    label: "Motion Bristol",
    venueName: "Motion",
    city: "Bristol",
    timezone: "Europe/London",
    officialCalendarUrl: "https://motion-bristol.com/whats-on/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@motionbristol",
  },
  {
    key: "uk_bristol_lakota",
    label: "Lakota Bristol",
    venueName: "Lakota",
    city: "Bristol",
    timezone: "Europe/London",
    officialCalendarUrl: "https://lakota.co.uk/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@lakotabristol",
  },
  // USA - Miami
  {
    key: "us_miami_clubspace",
    label: "Club Space Miami",
    venueName: "Club Space",
    city: "Miami",
    timezone: "America/New_York",
    officialCalendarUrl: "https://www.clubspace.com/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@clubspacemiami",
  },
  {
    key: "us_miami_factorytown",
    label: "Factory Town Miami",
    venueName: "Factory Town",
    city: "Miami",
    timezone: "America/New_York",
    officialCalendarUrl: "https://www.factorytown.com/events",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@factorytown_",
  },
  {
    key: "us_miami_m2",
    label: "M2 Miami",
    venueName: "M2 Miami",
    city: "Miami",
    timezone: "America/New_York",
    officialCalendarUrl: "https://www.m2miami.com/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@m2miami",
  },
  // USA - Chicago
  {
    key: "us_chicago_radius",
    label: "Radius Chicago",
    venueName: "Radius",
    city: "Chicago",
    timezone: "America/Chicago",
    officialCalendarUrl: "https://radius-chicago.com/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@radiuschicago",
  },
  {
    key: "us_chicago_smartbar",
    label: "Smartbar Chicago",
    venueName: "Smartbar",
    city: "Chicago",
    timezone: "America/Chicago",
    officialCalendarUrl: "https://smartbarchicago.com/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@smartbarchicago",
  },
  {
    key: "us_chicago_spybar",
    label: "Spybar Chicago",
    venueName: "Spybar",
    city: "Chicago",
    timezone: "America/Chicago",
    officialCalendarUrl: "https://www.spybarchicago.com/events/",
    rssUrl: null,
    icsUrl: null,
    snsAccount: "@spybarchicago",
  },
];
